import { PolicyFooter } from '../components/PolicyFooter.jsx';
import { InfoHeader } from '../components/InfoHeader.jsx';

/**
 * AI Processing disclosure.
 *
 * `ai_processing` is a REQUIRED consent and, like terms_of_service, had no
 * document behind it. This is the one users most deserve to read before
 * agreeing: it is the document that says their training information — and, if
 * they provide it, their injuries — is sent to a third party.
 *
 * ── aip-2026-08-27: WHAT THE AUDIT FOUND ──────────────────────────────────
 *
 * The "what is sent, precisely" list was written from memory rather than from
 * renderProfile(), and "precisely" is a promise. Three things reach the model
 * that this page did not name: the athlete's AGE, derived from the date of
 * birth this page said was not sent to the model; `progress_cadence`; and the
 * free-text note attached to a logged session, which is exactly the field
 * somebody types "shoulder felt off today" into.
 *
 * The date-of-birth sentence was the serious one. It was true about the
 * literal date and false about what is done with it - the prompt has an entire
 * section instructing the coach to program around age. A privacy disclosure
 * that is technically accurate about a field and silent about the inference
 * drawn from it is the pattern regulators name specifically.
 *
 * server/test/policyDisclosure.test.js now pins this list to renderProfile()
 * so the two cannot drift apart again without the build saying so.
 *
 * NOT TRANSLATED, deliberately. NOT reviewed by an attorney.
 */
export function AiProcessing() {
  return (
    <div className="page">
      <InfoHeader title="How Coach Diaz uses AI" version="Version aip-2026-08-28a" />

      <div className="card draft-banner">
        <strong>Draft — pending legal review.</strong>
        <p className="small">
          This describes what the application does today, checked against the source code. It has
          not been reviewed by an attorney and should not be relied on as a final legal document.
        </p>
      </div>

      <div className="card prose">
        <h2 className="h3">What changed in this version</h2>
        <p className="small">
          <strong>aip-2026-08-28a.</strong> If your goal is losing fat, whether you use a
          GLP-1 medication is now sent, when you have given it. The coach is instructed that it
          has no view on the medication itself.
        </p>
        <p className="small">
          <strong>aip-2026-08-27c.</strong> Your pronouns and your gender are sent, if you give
          them. The coach is instructed at length about what gender is <em>not</em> for — it does
          not change your loads, your exercises, the rate of progression it expects, or the
          structure of your block, and it is not a reason to raise body composition with you.
        </p>
        <p className="small">
          <strong>aip-2026-08-27b.</strong> Two new things are sent, and both are listed below:
          which gym chains you tick on the intake form, and the optional note you can type about
          which branch you mean. The note is stored exactly as you type it. There is no address
          lookup, no map and no location tracking anywhere in this product, and the gym names are
          only used to pre-fill the equipment box so you can correct it — the coach reads your
          equipment answer, not our idea of what that chain has.
        </p>
        <p className="small">
          <strong>aip-2026-08-27.</strong> We checked this page line by line against the code that
          actually builds the request, and it was incomplete. The previous version said your date
          of birth is &ldquo;not sent to the model&rdquo;. The date itself is not — but{' '}
          <strong>your age is</strong>, and the coach is instructed to use it, because recovery
          between heavy sessions slows as people get older. Saying the date stays behind while the
          age it produces goes out was a distinction that favored us, and it is corrected below.
          Two further things reach the model and were not listed: how quickly your lifts have been
          progressing, and any note you attach to a logged session. Because the document you
          previously agreed to did not describe these, this version supersedes the last one and you
          will be asked to agree again. What we send did not change; what this page admits to
          sending did.
        </p>

        <h2 className="h3">The short version</h2>
        <p>
          Your coaching conversation is generated by a large language model run by Anthropic. To
          answer you, we send Anthropic your message, the recent history of your conversation, and a
          summary of your training profile. <strong>If you have chosen to share injury or medical
          information, that is part of the summary</strong>, because a coach that does not know
          about your shoulder will program your shoulder badly.
        </p>

        <h2 className="h3">What is sent, precisely</h2>
        <ul>
          <li>Your training profile: experience, how quickly your lifts have been progressing, current lifts, bodyweight, units, equipment, days per week, goal, and competition date if you set one.</li>
          <li><strong>Your age in whole years</strong>, worked out from your date of birth. The date itself is not sent; the age is, and the coach is told to let it inform how much recovery you are given between heavy sessions.</li>
          <li>Your recent logged sessions — the movements, sets, reps, weights and RPE — <strong>including any note you wrote on a session</strong>. That box is free text and whatever you put in it goes with the session.</li>
          <li>Your best recorded set per lift.</li>
          <li>Your active program, if one has been written.</li>
          <li>Recovery information you chose to give: sleep, alcohol, nicotine, nutrition notes.</li>
          <li>Injuries and medical conditions you chose to give, and whether you are cleared to train.</li>
          <li>Numbers our own code worked out from the above and hands the model as answers: your next prescribed loads, rounded to the smallest plate you told us you own, your warm-up ramp, and your fueling ranges.</li>
          <li>
            Whether you use a GLP-1 medication, if you told us. Only "using", "considering" or
            "no" — never a drug name, a dose or a prescriber, and never the fact that you declined
            to answer. It is sent for one reason: on these medications much of the weight lost is
            muscle rather than fat, and that changes how your training is written.
          </li>
          <li>Your pronouns, and your gender if you gave one. Nothing physiological is inferred from either: where a figure genuinely differs, the coach is told to ask you rather than assume.</li>
          <li>Which gym chains you ticked, and the optional branch note you typed. The note goes as written; it is never turned into an address or a location.</li>
          <li>Reference material of ours that says nothing about you: the coaching instructions, and the exercise library with its links to demonstration videos.</li>
        </ul>

        <h2 className="h3">What is never sent</h2>
        <ul>
          <li>Your email address or password.</li>
          <li>Your date of birth itself.</li>
          <li>Your location. Not an address, not coordinates, not an IP-derived guess. The branch note is whatever you typed and nothing looks it up.</li>
          <li>Any other user&rsquo;s data. The database restricts every query to your own rows, so a request made for you cannot return anyone else&rsquo;s.</li>
          <li>Credentials of any kind. There are none in the context the model receives.</li>
        </ul>

        <h2 className="h3">Where the request goes</h2>
        <p>
          Your browser never contacts Anthropic directly. Requests go to our server, which holds the
          API key and adds it there. The key is never sent to your browser and is not present in the
          JavaScript you download.
        </p>

        <h2 className="h3">The model can be wrong</h2>
        <p>
          Language models produce confident text, including when they are mistaken. Treat the
          coaching as informed suggestion, not instruction from an expert who can see you. The
          decisions that most affect your safety — whether you need medical clearance, and how much
          weight goes on the bar next — are calculated by our own code and given to the model as
          answers, precisely so they do not depend on it getting the arithmetic right.
        </p>

        <h2 className="h3">What we log</h2>
        <p>
          Application logs record that a request happened and how it turned out. They do not record
          your injuries, your medical conditions, your recovery information, or anything you or the
          coach said. Redaction happens in one place in the code, on the way into the logger, so it
          cannot be skipped by someone forgetting at a call site.
        </p>
        <p>
          Two things in those logs are about you rather than about the request. When you save your
          profile we record <em>which fields you changed</em> — the names of the fields, never the
          values — because without that a failed save cannot be diagnosed. And every coaching reply
          is recorded with how many tokens it used and what it cost us, kept both in the log and in
          a row in our database. Neither contains any message content, and neither is used for
          advertising or profiling.
        </p>

        <h2 className="h3">Declining</h2>
        <p>
          This consent is required, because the coaching conversation <em>is</em> the product and it
          cannot happen without sending your message to a model. Consent to share{' '}
          <em>health information</em> is separate and is not required — you can use Coach Diaz
          without telling it about injuries, and it will simply program more conservatively. You can
          withdraw that separately at any time, and doing so erases the health fields from your
          profile.
        </p>
      </div>

      <PolicyFooter fallback="/faq" />
    </div>
  );
}
