import { Link } from 'react-router-dom';

/**
 * AI Processing disclosure.
 *
 * `ai_processing` is a REQUIRED consent and, like terms_of_service, had no
 * document behind it. This is the one users most deserve to read before
 * agreeing: it is the document that says their training information — and, if
 * they provide it, their injuries — is sent to a third party.
 *
 * NOT TRANSLATED, deliberately. NOT reviewed by an attorney.
 */
export function AiProcessing() {
  return (
    <div className="page">
      <header className="page-header">
        <h1>How Coach Diaz uses AI</h1>
        <p className="muted small">Version aip-2026-08-24</p>
      </header>

      <div className="card draft-banner">
        <strong>Draft — pending legal review.</strong>
        <p className="small">
          This describes what the application does today, checked against the source code. It has
          not been reviewed by an attorney and should not be relied on as a final legal document.
        </p>
      </div>

      <div className="card prose">
        <h2 className="h3">The short version</h2>
        <p>
          Your coaching conversation is generated by a large language model run by Anthropic. To
          answer you, we send Anthropic your message, the recent history of your conversation, and a
          summary of your training profile. <strong>If you have chosen to share injury or medical
          information, that is part of the summary</strong>, because a coach that does not know
          about your shoulder will program your shoulder badly.
        </p>

        <h2 className="h3">What is sent, precisely</h2>
        <ul>
          <li>Your training profile: experience, current lifts, bodyweight, units, equipment, days per week, goal, and competition date if you set one.</li>
          <li>Your recent logged sessions and your best set per lift.</li>
          <li>Your active program, if one has been written.</li>
          <li>Recovery information you chose to give: sleep, alcohol, nicotine, nutrition notes.</li>
          <li>Injuries and medical conditions you chose to give, and whether you are cleared to train.</li>
          <li>Your date of birth is used to check you are 18 or over. It is not sent to the model.</li>
        </ul>

        <h2 className="h3">What is never sent</h2>
        <ul>
          <li>Your email address or password.</li>
          <li>Any other user&rsquo;s data. The database restricts every query to your own rows, so a request made for you cannot return anyone else&rsquo;s.</li>
          <li>Credentials of any kind. There are none in the context the model receives.</li>
        </ul>

        <h2 className="h3">Where the request goes</h2>
        <p>
          Your browser never contacts Anthropic directly. Requests go to our server, which holds the
          API key and adds it there. The key is never sent to your browser and is not present in the
          JavaScript you download.
        </p>

        <h2 className="h3">The model can be wrong</h2>
        <p>
          Language models produce confident text, including when they are mistaken. Treat the
          coaching as informed suggestion, not instruction from an expert who can see you. The
          decisions that most affect your safety — whether you need medical clearance, and how much
          weight goes on the bar next — are calculated by our own code and given to the model as
          answers, precisely so they do not depend on it getting the arithmetic right.
        </p>

        <h2 className="h3">What we log</h2>
        <p>
          Application logs record that a request happened, and its outcome. They do not record your
          injuries, your medical conditions, your recovery information, or the content of your
          conversation. Redaction happens in one place in the code so it cannot be skipped by
          someone forgetting.
        </p>

        <h2 className="h3">Declining</h2>
        <p>
          This consent is required, because the coaching conversation <em>is</em> the product and it
          cannot happen without sending your message to a model. Consent to share{' '}
          <em>health information</em> is separate and is not required — you can use Coach Diaz
          without telling it about injuries, and it will simply program more conservatively. You can
          withdraw that separately at any time, and doing so erases the health fields from your
          profile.
        </p>
      </div>

      <div className="row gap">
        <Link className="link" to="/consent">
          Back
        </Link>
      </div>
    </div>
  );
}
