-- =============================================================================
-- 0010_consent_ledger_monotonic_ordering.sql
--
-- Fixes a correctness bug in the consent ledger, found while testing it.
--
-- "Current consent" was the most recent row by created_at, defaulting to
-- now(). In Postgres now() is TRANSACTION START TIME, identical for every
-- statement in a transaction. A grant and a withdrawal recorded in the same
-- transaction therefore carried the same timestamp, and
-- `order by created_at desc limit 1` chose between them arbitrarily.
--
-- It chose the grant. A user who withdrew consent was still recorded as having
-- given it, and health data could still be written. For an audit ledger of a
-- health-privacy consent, that is close to the worst available outcome: the
-- record says the user agreed when they did not.
--
-- Not only a test artefact - any request recording two consent changes
-- together, such as "withdraw health data, keep terms", hits the same tie.
--
-- Clocks tie, and go backwards under NTP adjustment. They are the wrong
-- primitive for ordering events you must be able to defend. An identity
-- column is strictly monotonic, which is what "most recent" should mean here.
-- =============================================================================

alter table public.consent_records
  add column seq bigint generated by default as identity;

alter table public.consent_records
  alter column created_at set default clock_timestamp();

update public.consent_records set seq = seq where seq is null;
alter table public.consent_records alter column seq set not null;

create index consent_records_user_type_seq_idx
  on public.consent_records (user_id, consent_type, seq desc);
drop index if exists consent_records_user_type_idx;

comment on column public.consent_records.seq is
  'Monotonic event order. Authoritative for "most recent consent" - created_at can tie within a transaction and must not be used for ordering.';

create or replace function public.has_active_consent(p_consent_type text)
returns boolean language sql security invoker stable set search_path = ''
as $$
  select coalesce(
    (select granted from public.consent_records
      where user_id = auth.uid() and consent_type = p_consent_type
      order by seq desc limit 1),
    false
  );
$$;
